[profile.default]
solc_version = "0.8.19"
out = 'artifacts/foundry'
cache_path = 'cache/foundry'
fuzz_runs = 100
optimizer_runs = 10_000
optimizer = true
no_match_path = "test/differential/*"
libs = ["node_modules", "lib"]
