on: workflow_call

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/.yarn/cache
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-nodemodules
      - name: Install packages
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --immutable

  check:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/.yarn/cache
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-nodemodules
      - name: scan (tsc + prettier + solhint)
        run: yarn scan

  static-analysis:
    name: Static analysis (slither)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run slither
        uses: crytic/slither-action@v0.2.0
        continue-on-error: true
        with:
          fail-on: 'config'
  test:
    name: forge test
    runs-on: ubuntu-latest
    env:
      FOUNDRY_PROFILE: ci
    steps:
      - uses: actions/checkout@v3
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Setup forge
        working-directory: apps/contract
        run: forge install
      - name: Run tests
        working-directory: apps/contract
        run: forge test  --gas-report
