on: workflow_call

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: |
            ${{ github.workspace }}/.yarn/cache
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/apps/client-admin/node_modules
            ${{ github.workspace }}/apps/client-public/node_modules
            ${{ github.workspace }}/apps/contract/artifacts
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/foundry.toml') }}
      - name: Install packages
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --immutable

  check:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/.yarn/cache
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/foundry.toml') }}
      - name: scan (tsc + prettier + solhint)
        run: yarn scan

  static-analysis:
    name: Static analysis (slither)
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/apps/contract/artifacts
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/foundry.toml') }}
      - name: Run slither
        uses: crytic/slither-action@v0.3.0
        continue-on-error: true
        with:
          target: apps/contract
          fail-on: 'config'
          ignore-compile: true

  integration-test:
    name: test
    runs-on: ubuntu-latest
    needs: check
    env:
      FOUNDRY_PROFILE: ci
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/.yarn/cache
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/foundry.toml') }}
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Setup forge
        working-directory: apps/contract
        run: forge install
      - name: forge build
        working-directory: apps/contract
        run: |
          forge --version
          forge build --sizes
        id: build
      - name: (forge) contract tests
        working-directory: apps/contract
        run: forge test --gas-report
      - name: (hardhat) interface tests
        working-directory: apps/contract
        run: yarn test:hardhat
