on: workflow_call

jobs:
  compile:
    name: Compile contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: foundry-rs/foundry-toolchain@eef83bf8f46f7ccaae8377bb99cfa3a5aa40c348
        with:
          version: nightly
      - name: Setup forge
        working-directory: apps/contract
        run: forge install
      - name: forge build
        working-directory: apps/contract
        run: |
          forge --version
          forge build --sizes
        id: build
      - uses: actions/upload-artifact@v4
        with:
          name: abi
          path: apps/contract/artifacts/foundry/

  contract-test:
    name: contract tests
    runs-on: ubuntu-latest
    needs: compile
    env:
      FOUNDRY_PROFILE: ci
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/download-artifact@v4
        with:
          name: abi
          path: apps/contract/artifacts/foundry/
      - uses: foundry-rs/foundry-toolchain@eef83bf8f46f7ccaae8377bb99cfa3a5aa40c348
        with:
          version: nightly
      - name: contract tests
        working-directory: apps/contract
        run: forge test --gas-report

  static-analysis:
    name: Static analysis (slither)
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/download-artifact@v4
        with:
          name: abi
          path: apps/contract/artifacts/foundry/
      - name: Run slither
        uses: crytic/slither-action@v0.3.0
        continue-on-error: true
        with:
          target: apps/contract
          fail-on: 'config'
          ignore-compile: true
