name: CI

on: push

jobs:
  node:
    uses: ./.github/workflows/_node.yml

  forge:
    uses: ./.github/workflows/_forge.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
