name: CI

on: push

jobs:
  ci:
    uses: ./.github/workflows/_ci.yml

  build:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/.yarn/cache
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/apps/client-admin/node_modules
            ${{ github.workspace }}/apps/client-public/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/foundry.toml') }}
      - name: Build client-admin
        run: yarn workspace client-admin turbo build
      - name: Build client-public
        run: yarn workspace client-public turbo build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
